import type { Event, Profile, Venue } from "@/types";

export const MOCK_VENUES: Venue[] = [
  {
    id: "v1",
    name: "Club Sonderbar",
    address: "Luitpoldplatz 5, 94469 Deggendorf",
    lat: 48.8312,
    lng: 12.9601,
    google_place_id: null,
    website: "https://sonderbar-deggendorf.de",
    instagram: "@sonderbar_deg",
    phone: null,
    verified: true,
    owner_id: null,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "v2",
    name: "Wirtshaus zur Alten Post",
    address: "Oberer Stadtplatz 2, 94469 Deggendorf",
    lat: 48.8321,
    lng: 12.9615,
    google_place_id: null,
    website: null,
    instagram: null,
    phone: null,
    verified: true,
    owner_id: null,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "v3",
    name: "Stadthalle Deggendorf",
    address: "Edlmairstraße 2, 94469 Deggendorf",
    lat: 48.833,
    lng: 12.957,
    google_place_id: null,
    website: "https://stadthalle-deggendorf.de",
    instagram: null,
    phone: null,
    verified: true,
    owner_id: null,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "v4",
    name: "Kneitinger Keller",
    address: "Galgenbergstraße 18, 93053 Regensburg",
    lat: 49.0134,
    lng: 12.1016,
    google_place_id: null,
    website: null,
    instagram: null,
    phone: null,
    verified: true,
    owner_id: null,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "v5",
    name: "Dreiländerhalle Passau",
    address: "Messestraße 12, 94036 Passau",
    lat: 48.5665,
    lng: 13.4319,
    google_place_id: null,
    website: null,
    instagram: null,
    phone: null,
    verified: true,
    owner_id: null,
    created_at: "2026-01-01T00:00:00Z",
  },
];

export const MOCK_PROFILES: Profile[] = [
  {
    id: "u1",
    username: "lnup_team",
    display_name: "LNUP Team",
    avatar_url: null,
    role: "admin",
    trust_score: 9999,
    rank: "city_icon",
    email_verified: true,
    phone_verified: true,
    created_at: "2026-01-01T00:00:00Z",
    events_posted: 45,
    events_confirmed: 45,
    reports_count: 0,
  },
  {
    id: "u2",
    username: "sarah_m",
    display_name: "Sarah M.",
    avatar_url: null,
    role: "verified_user",
    trust_score: 327,
    rank: "party_planner",
    email_verified: true,
    phone_verified: true,
    created_at: "2026-02-01T00:00:00Z",
    events_posted: 28,
    events_confirmed: 24,
    reports_count: 0,
  },
  {
    id: "u3",
    username: "max_deg",
    display_name: "Max D.",
    avatar_url: null,
    role: "verified_user",
    trust_score: 89,
    rank: "regular",
    email_verified: true,
    phone_verified: false,
    created_at: "2026-02-10T00:00:00Z",
    events_posted: 8,
    events_confirmed: 6,
    reports_count: 0,
  },
  {
    id: "u4",
    username: "newuser42",
    display_name: "Neuer User",
    avatar_url: null,
    role: "user",
    trust_score: 3,
    rank: "newbie",
    email_verified: true,
    phone_verified: false,
    created_at: "2026-02-18T00:00:00Z",
    events_posted: 1,
    events_confirmed: 0,
    reports_count: 0,
  },
];

function getUpcomingDate(daysFromNow: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().split("T")[0];
}

export const MOCK_EVENTS: Event[] = [
  {
    id: "e1",
    title: "90s Techno Night",
    description:
      "Old School Techno mit DJ Markov. Lasershow ab Mitternacht. Eintritt vor 23 Uhr nur 5€!",
    venue_id: "v1",
    venue: MOCK_VENUES[0],
    series_id: null,
    event_date: getUpcomingDate(0),
    time_start: "21:00",
    time_end: "04:00",
    category: "nightlife",
    price_info: "5€",
    source_type: "verified_organizer",
    source_url: null,
    created_by: "u2",
    creator: MOCK_PROFILES[1],
    status: "active",
    ai_confidence: null,
    image_url: null,
    created_at: "2026-02-15T00:00:00Z",
    saves_count: 42,
    going_count: 87,
    confirmations_count: 12,
    photos_count: 7,
    is_saved: false,
    is_going: false,
  },
  {
    id: "e2",
    title: "Cocktail & Jazz Abend",
    description:
      "Live Jazz Trio ab 19 Uhr. 2-für-1 Cocktails den ganzen Abend. Reservierung empfohlen!",
    venue_id: "v2",
    venue: MOCK_VENUES[1],
    series_id: null,
    event_date: getUpcomingDate(0),
    time_start: "19:00",
    time_end: "23:00",
    category: "food_drink",
    price_info: "Eintritt frei",
    source_type: "verified_organizer",
    source_url: null,
    created_by: "u1",
    creator: MOCK_PROFILES[0],
    status: "active",
    ai_confidence: null,
    image_url: null,
    created_at: "2026-02-14T00:00:00Z",
    saves_count: 28,
    going_count: 34,
    confirmations_count: 8,
    photos_count: 3,
    is_saved: true,
    is_going: true,
  },
  {
    id: "e3",
    title: "Wanda — Live in Concert",
    description:
      "Die österreichische Indie-Rock Band Wanda auf Deutschland-Tour! Support: Anger.",
    venue_id: "v3",
    venue: MOCK_VENUES[2],
    series_id: null,
    event_date: getUpcomingDate(1),
    time_start: "20:00",
    time_end: "23:00",
    category: "concert",
    price_info: "35€",
    source_type: "api_eventbrite",
    source_url: "https://eventbrite.de/e/wanda-deggendorf",
    created_by: null,
    status: "active",
    ai_confidence: 0.98,
    image_url: null,
    created_at: "2026-02-10T00:00:00Z",
    saves_count: 156,
    going_count: 213,
    confirmations_count: 0,
    photos_count: 0,
    is_saved: false,
    is_going: false,
  },
  {
    id: "e4",
    title: "Street Food Markt",
    description:
      "Über 20 Food Trucks aus der Region. Craft Beer, internationale Küche und Live-Musik.",
    venue_id: "v3",
    venue: MOCK_VENUES[2],
    series_id: null,
    event_date: getUpcomingDate(2),
    time_start: "11:00",
    time_end: "22:00",
    category: "festival",
    price_info: "Eintritt frei",
    source_type: "platform",
    source_url: null,
    created_by: "u1",
    creator: MOCK_PROFILES[0],
    status: "active",
    ai_confidence: null,
    image_url: null,
    created_at: "2026-02-08T00:00:00Z",
    saves_count: 89,
    going_count: 142,
    confirmations_count: 0,
    photos_count: 0,
    is_saved: false,
    is_going: false,
  },
  {
    id: "e5",
    title: "Yoga im Park",
    description:
      "Kostenlose Yoga-Session im Stadtpark. Bring deine eigene Matte mit! Alle Level willkommen.",
    venue_id: "v3",
    venue: { ...MOCK_VENUES[2], name: "Stadtpark Deggendorf", address: "Stadtpark, 94469 Deggendorf" },
    series_id: null,
    event_date: getUpcomingDate(3),
    time_start: "10:00",
    time_end: "11:30",
    category: "sports",
    price_info: "Kostenlos",
    source_type: "verified_user",
    source_url: null,
    created_by: "u3",
    creator: MOCK_PROFILES[2],
    status: "active",
    ai_confidence: null,
    image_url: null,
    created_at: "2026-02-17T00:00:00Z",
    saves_count: 19,
    going_count: 23,
    confirmations_count: 5,
    photos_count: 2,
    is_saved: false,
    is_going: false,
  },
  {
    id: "e6",
    title: "House Party am Hafen",
    description: "Guter DJ kommt, vertraut mir. Bringt Freunde mit!",
    venue_id: "v1",
    venue: { ...MOCK_VENUES[0], name: "Nähe Donauhafen", address: "Hafenstraße, 94469 Deggendorf" },
    series_id: null,
    event_date: getUpcomingDate(2),
    time_start: "23:00",
    time_end: null,
    category: "nightlife",
    price_info: "Kostenlos",
    source_type: "community",
    source_url: null,
    created_by: "u4",
    creator: MOCK_PROFILES[3],
    status: "active",
    ai_confidence: null,
    image_url: null,
    created_at: "2026-02-19T00:00:00Z",
    saves_count: 2,
    going_count: 4,
    confirmations_count: 0,
    photos_count: 0,
    is_saved: false,
    is_going: false,
  },
  {
    id: "e7",
    title: "Dult Regensburg 2026",
    description:
      "Das traditionelle Volksfest in Regensburg. Fahrgeschäfte, Bierzelte, Live-Musik und mehr!",
    venue_id: "v4",
    venue: MOCK_VENUES[3],
    series_id: null,
    event_date: getUpcomingDate(5),
    time_start: "10:00",
    time_end: "23:00",
    category: "festival",
    price_info: "Eintritt frei",
    source_type: "api_ticketmaster",
    source_url: "https://ticketmaster.de/dult-regensburg",
    created_by: null,
    status: "active",
    ai_confidence: 0.95,
    image_url: null,
    created_at: "2026-02-01T00:00:00Z",
    saves_count: 312,
    going_count: 478,
    confirmations_count: 0,
    photos_count: 0,
    is_saved: false,
    is_going: false,
  },
];
